language: go

go:
  - 1.5

before_install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/cihub/seelog
  - export PATH=$PATH:/home/travis/gopath/bin:/usr/local/cassandra/bin

install:
  - go get -v .

script:
  - bash integration.sh
